version: "3"
services:
  database:
    image: postgres:13
    ports: [5432:5432]
    network_mode: "host"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./migrations/faculty_manager.sql:/docker-entrypoint-initdb.d/init.sql

    